// Mocks generated by Mockito 5.4.4 from annotations
// in remindme/test/hive_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:remindme/services/notification_service.dart' as _i3;
import 'package:remindme/task.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterLocalNotificationsPlugin_0 extends _i1.SmartFake
    implements _i2.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i3.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
        Invocation.getter(#flutterLocalNotificationsPlugin),
        returnValue: _FakeFlutterLocalNotificationsPlugin_0(
          this,
          Invocation.getter(#flutterLocalNotificationsPlugin),
        ),
      ) as _i2.FlutterLocalNotificationsPlugin);

  @override
  set flutterLocalNotificationsPlugin(
          _i2.FlutterLocalNotificationsPlugin?
              _flutterLocalNotificationsPlugin) =>
      super.noSuchMethod(
        Invocation.setter(
          #flutterLocalNotificationsPlugin,
          _flutterLocalNotificationsPlugin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleWeekdayNotifications(
    List<_i5.Task>? items,
    int? hour,
    int? minute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleWeekdayNotifications,
          [
            items,
            hour,
            minute,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.PendingNotificationRequest>>
      getScheduledNotifications() => (super.noSuchMethod(
            Invocation.method(
              #getScheduledNotifications,
              [],
            ),
            returnValue: _i4.Future<List<_i2.PendingNotificationRequest>>.value(
                <_i2.PendingNotificationRequest>[]),
          ) as _i4.Future<List<_i2.PendingNotificationRequest>>);
}
